version: '3'
services:
  flask:
    build: ./deposit_service
    container_name: deposit_service
    environment:
      # для отладки
      - FLASK_ENV=development
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
      ##
    # Перезапускаем сервис в случае падения
    restart: on-failure
    # mapping
    volumes:
      - ./:/deposit_service
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5010:5010"
    command: gunicorn -w 4 -b 0.0.0.0:5010 app_gu:service_app
